export const cardLibrary = {
  // ── MONSTERS ──────────────────────────────────────────
  "Doro": { name: "Doro", type: "monster", attack: 1, defense: 2, cost: 1 },
  "Usagi": { name: "Usagi", type: "monster", attack: 0, defense: 6, cost: 0 },
  "Iron Golem": { name: "Iron Golem", type: "monster", attack: 4, defense: 5, cost: 4 },
  "Shadow Wraith": { name: "Shadow Wraith", type: "monster", attack: 5, defense: 2, cost: 3 },
  "Stone Sentinel": { name: "Stone Sentinel", type: "monster", attack: 2, defense: 7, cost: 3 },
  "Flame Drake": { name: "Flame Drake", type: "monster", attack: 6, defense: 3, cost: 5 },
  "Void Stalker": { name: "Void Stalker", type: "monster", attack: 7, defense: 1, cost: 5 },
  "Crystal Golem": { name: "Crystal Golem", type: "monster", attack: 3, defense: 8, cost: 5 },
  "Bone Archer": { name: "Bone Archer", type: "monster", attack: 4, defense: 2, cost: 2 },
  "Plague Rat": { name: "Plague Rat", type: "monster", attack: 2, defense: 1, cost: 1 },
  "Thunder Boar": { name: "Thunder Boar", type: "monster", attack: 5, defense: 4, cost: 4 },
  "Mire Toad": { name: "Mire Toad", type: "monster", attack: 1, defense: 4, cost: 1 },
  "Ember Fox": { name: "Ember Fox", type: "monster", attack: 3, defense: 2, cost: 2 },
  "Ancient Tortoise": { name: "Ancient Tortoise", type: "monster", attack: 1, defense: 9, cost: 4 },
  "Rift Serpent": { name: "Rift Serpent", type: "monster", attack: 6, defense: 2, cost: 4 },
  "Dusk Knight": { name: "Dusk Knight", type: "monster", attack: 5, defense: 5, cost: 5 },
  "Mud Elemental": { name: "Mud Elemental", type: "monster", attack: 3, defense: 5, cost: 3 },
  "Banshee": { name: "Banshee", type: "monster", attack: 4, defense: 1, cost: 2 },
  "Granite Titan": { name: "Granite Titan", type: "monster", attack: 7, defense: 7, cost: 6 },
  "Gloom Bat": { name: "Gloom Bat", type: "monster", attack: 2, defense: 2, cost: 1 },

  // ── SPELLS ────────────────────────────────────────────
  "Doro's Roar": { name: "Doro's Roar", type: "spell", attack: 0, defense: 0, cost: 2, effect: "All your monsters gain +2 ATK until end of turn." },
  "Fireball": { name: "Fireball", type: "spell", attack: 0, defense: 0, cost: 3, effect: "Deal 3 damage directly to the opponent's HP." },
  "Stone Wall": { name: "Stone Wall", type: "spell", attack: 0, defense: 0, cost: 2, effect: "One of your monsters gains +4 DEF until end of turn." },
  "Dark Rift": { name: "Dark Rift", type: "spell", attack: 0, defense: 0, cost: 4, effect: "Destroy one monster on the opponent's field." },
  "Mend": { name: "Mend", type: "spell", attack: 0, defense: 0, cost: 1, effect: "Restore 2 HP to yourself." },
  "Phantom Strike": { name: "Phantom Strike", type: "spell", attack: 0, defense: 0, cost: 3, effect: "One of your monsters attacks twice this turn." },
  "Cursed Ground": { name: "Cursed Ground", type: "spell", attack: 0, defense: 0, cost: 2, effect: "Opponent's monsters lose -2 ATK until end of turn." },
  "Veil of Shadow": { name: "Veil of Shadow", type: "spell", attack: 0, defense: 0, cost: 3, effect: "Your monsters cannot be targeted this turn." },
  "Tremor": { name: "Tremor", type: "spell", attack: 0, defense: 0, cost: 2, effect: "Deal 1 damage to all monsters on the opponent's field." },
  "Ancient Seal": { name: "Ancient Seal", type: "spell", attack: 0, defense: 0, cost: 4, effect: "Negate the effect of one spell on the field." },
  "Swift Blade": { name: "Swift Blade", type: "spell", attack: 0, defense: 0, cost: 1, effect: "One of your monsters gains +3 ATK for one attack." },
  "Plague Cloud": { name: "Plague Cloud", type: "spell", attack: 0, defense: 0, cost: 3, effect: "Deal 2 damage to the opponent's HP for each monster they control." },
  "Mirror Shield": { name: "Mirror Shield", type: "spell", attack: 0, defense: 0, cost: 2, effect: "Reflect the next spell played against you back at the opponent." },
  "Soul Drain": { name: "Soul Drain", type: "spell", attack: 0, defense: 0, cost: 4, effect: "Opponent discards one card from their hand to the gallows." },
  "Void Pulse": { name: "Void Pulse", type: "spell", attack: 0, defense: 0, cost: 3, effect: "Draw two cards from your deck." },
}